# Generated by Django 4.2 on 2023-04-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core.post',
        ),
    ]
